### ISSUE TITLE
CrypoUtils.generateAESKey() returns constant String"AES"

### ISSUE THREAD

**Issue by d-schmidt** [tunjos/java-crypto-utils#1]
https://github.com/tunjos/java-crypto-utils/blob/54b44eb25d64c69c77ea298d30e7a0ca958a4107/src/main/java/co/tunjos/crypto/crypto/CryptoUtils.java#L42

The test does not catch this flaw.

**Comment by tunjos** [comment]
Fixed! :ok_hand:
